### ISSUE TITLE
Change app's name

### ISSUE THREAD

**Issue by cketti** [scoute-dich/K9-MailClient#6]
To avoid confusion please change the name of the app. Either make it completely different or add "inofficial" to signify that the K-9 Mail project is not the creator of this variant.

-cketti
(K-9 Mail Project Lead)

**Comment by scoute-dich** [comment]
I will change the app name in "k9 material (unofficial)", if that's ok for the k9 team. Btw thanks for your great work. Using k9 since the early android days.

Are there any plans to bring material design to k9? I know there were long discussions in the issue list, but I'm not sure about the progress and "official" plans...

Regards
Gaukler Faun

**Comment by cketti** [comment]
The suggested name is fine.

We do have the intention to update the UI with Material Design. But there's no public roadmap.

**Comment by scoute-dich** [comment]
I changed the name.
Is there a specific branch existing to test the progress of material design? Or where can I follow the progress?

Regards
Gaukler Faun
